### ISSUE TITLE
Scrum Update 1

### ISSUE THREAD

**Issue by phreid** [nyananu/somethingBorrowed#1]

**Comment by phreid** [comment]
csid - f2u8e

**What did you work on this past iteration?**

Brainstormed our set of project requirements and tasks. Worked on writing the project design document, requirements, and tasks. 

**What were any major challenges/issues you ran into?**

No issues.

**What do you plan to work on this coming iteration?**

Work on building components for the minimal frontend.

**Comment by imogenem** [comment]
csid - a8v2b 

1. What did you work on this past iteration?

We worked on project ideation phase where we talked through a few alternative projects and then discussed the requirements for our final project choice. We then divided up work to finalize the project description, requirements breakdown, and prototype drawings.

3. What were any major challenges you ran into?

We spent some time figuring out how to classify the requirements, as we had varying interpretations of the project and what is needed for the minimum viable product.

4. What do you plan to work on for this coming iteration?

Setting up the code base and the first iteration of the front-end.

**Comment by nyananu** [comment]
csid - i4y2b

**What did you work on this past iteration?**
Each member worked on writing Project Description for their idea, so we came up with 4 ideas in total. From that we had a meeting to decide + discuss with TA our final idea. Then we fine-tuned the minimal, standard and stretch requirements for the project, as well as wireframing, filling forms, making repo, adding members as collaborators and setting up the foundation of the project.

**What were any major challenges/issues you ran into?**
Nothing major. Some time was spent in deciding which requirement to put in standard goal or stretch goal.

**What do you plan to work on this coming iteration?**
Set up the project using react app, and break down a couple of the minimal requirements into actual tickets/issues to be done. Hopefully implement the landing page with necessary components for login etc.

**Comment by cailors** [comment]
u7a3b

**What did you work on this past iteration (2 weeks)?**
Discussed the features to be included in the project; made design decisions and include them in the prototype sketch.

**What were any major issues/challenges you ran into?**
Estimating the time/work required for each feature and debating on which one should be labeled as stretch goals and minimal requirements. 

**What do you plan to work on for this coming iteration (2 weeks)**
Staring to code the project and working on the frontend of the features.
