### ISSUE TITLE
Duplicate constants

### ISSUE THREAD

**Issue by imogenem** [nyananu/somethingBorrowed#113]
We have the constants declared at the root and frontend folders, can we switch to using just one so we don't miss potential conflicts?

**Comment by phreid** [comment]
i had to split them when i did the deployment, because React doesn't let you import things from outside the React src folder. it's annoying, but the workarounds i looked up seemed like they weren't worth the trouble.

**Comment by imogenem** [comment]
Ahh okay makes sense
