### ISSUE TITLE
login page: incorrect username error is the incorrect size

### ISSUE THREAD

**Issue by phreid** [nyananu/somethingBorrowed#125]
@nyananu on the login page redesign, the incorrect username error spans the entire logo instead of being the same size as the other buttons: 

![image](https://user-images.githubusercontent.com/6674293/182776988-a956681b-3aca-4697-9802-dae4ab4beafc.png)

**Comment by nyananu** [comment]
https://github.com/phreid/somethingBorrowed/pull/149

This PR deals with this issue, so I'm closing this
