### ISSUE TITLE
Scrum 3 Update

### ISSUE THREAD

**Issue by phreid** [nyananu/somethingBorrowed#57]

**Comment by phreid** [comment]
Paul Reid

**What did you work on this past iteration?**
I created an Express server and set up our main API routes for items, users, and login/logout. Also added fake user login with redux to our frontend. 

**What were any major challenges/issues you ran into?**

No issues.

**What do you plan to work on this coming iteration?**

Add mongodb to our website backend.

**Comment by imogenem** [comment]
Imogene McDonald

Worked on this week:
I added props to the ItemCard to allow conditional rendering of buttons depending on where they are displayed (ie. can a user delete, borrow edit). I also created the modal and redux actions for editing an item.

Major challenges?
We initially ran into issues with creating the items in the state, but after figuring out how to add in unique id's in the state we were able to get the actions working.

Plan to work on this coming iteration?
We will add our database and API calls, as well as develop a few more features for the ui

**Comment by nyananu** [comment]
Anusha Saleem

What did you work on this past iteration?
I implemented the add delete actions through redux toolkit, and implemented page for profile and some css work

What were any major challenges/issues you ran into?

No issues

What do you plan to work on this coming iteration?

Add mongodb to our website backend.

**Comment by cailors** [comment]
Hanting Du

**What did you work on this past iteration?**
I created the form of the extendable search bar.

**What were any major challenges/issues you ran into?**
Using css file to make the search bar extendable.

**What do you plan to work on this coming iteration?**
The minimal and standard requirement related to Marketplace page.
